### PR TITLE
Add a form to prepare new dev json

### PR DESCRIPTION
**Pull request by Mohd-PH**
Good morning

In this pull request I've added a form in the website to generate new dev's json easily

It pulls dev's repos after they insert their github username so the user can select the repo that they want to add along with needed like topics, license .. etc

Doing so I believe it will decrease the need from our side to pull the data using github workflow

Hope it helps 😄

### CODE REVIEW

**Comment by Alaboudi1** [comment]
Hey, this really great! Few questions though:

1. What happens if someone is already on the list but needs to add new projects?
2. The pick your project option  (إختر مشروعك) does not show anything even after putting my GitHub URL; why?
3. How hard is it to make users log in through GitHub (OAuth) and makes the pull request entirely from the website? I know this is kinda a stretch, but I am curious to know if you have looked into this and have some idea about the effort needed to implement such a thing! This may completely remove the need for the flaky GitHub workflow.

Thank you so much and looking forwards to adding this feature.

**Comment by Alaboudi1** [comment]
Yeah, we do not want any backend. It is undoubtedly an overkill for this project. I was thinking of just doing that in js to make the contribution easier. Anyway, this is something we may look at later, but for this pull request, we need to make sure that it supports all types of scenarios for adding and updating projects. Otherwise, it is just going to be confusing when to use this vs just edit the JSON, right?

**Comment by Alaboudi1** [comment]
Great, thanks!

**Comment by Mohd-PH** [comment]
Just updated 😃

**Comment by Alaboudi1** [comment]
Looks good! Thank you for your contribution @Mohd-PH !!

**Comment by Mohd-PH** [comment]
My pleasure 😄

**Pull request merged**
