### PR TITLE
Add(Ahmed Rowaihi): react-native-i18n-storage

### PR DESCRIPTION
**Pull request by ahmedrowaihi**

### CODE REVIEW

**Comment by Mohd-PH** [comment]
Thank you 🚀🚀🚀🚀🚀

**Comment by ahmedrowaihi** [comment]
@Mohd-PH check readme is not updating...

**Comment by Mohd-PH** [comment]
Yeah I'll do it manually and try to fix the github action asap 

Thanks 😊

**Comment by Mohd-PH** [comment]
Hala @Alaboudi1 

I've looked into the issue and tried to run the same workflow in my private clone of this repo

I believe it is a permission issue

We need the `write` permission for the `contents` scope in this organization settings

Only the admin can set the settings

Here how you can enable this permission:

[https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#configuring-the-default-github_token-permissions](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#configuring-the-default-github_token-permissions)

Looking forward for your input and thank you 🚀

**Comment by Alaboudi1** [comment]
@Mohd-PH I just gave you admin permission to debug this issue.

**Comment by Mohd-PH** [comment]
@Alaboudi1 everything works as it should now 

Thank you 

I think the previous documentation link was old and not accurate

I followed this blog post by github about permission and specified them in the workflow yaml file

[GitHub Actions: Control permissions for GITHUB_TOKEN](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/)

Also fixed an issue where markdown fails to parse empty `td` tags

**Comment by Mohd-PH** [comment]
My pleasure 😄

**Pull request merged**
