### PR TITLE
Add projects list to website

### PR DESCRIPTION
**Pull request by Mohd-PH**
Hala

In this pull request, I had the opportunity to add a section to display a project list/table in the website, as a new tab next to developers tab

Screenshot

Along with a github workflow that extracts projects' data from github with after every approved pull request 

Hope it adds something 😄

### CODE REVIEW

**Comment by Alaboudi1** [comment]
Great work on improving the information displayed for each project! However, introducing a new tab named "projects" may potentially cause confusion, as users could misunderstand this as representing a new dataset instead of a different presentation format of the same dev.json file. What about a dropdown menu that enables users to switch between a 'compact view' and a 'detail view'? The compact view could retain the existing display while the detail view showcases the newly added information for each project.

Incorporating a search function could be another valuable feature, although it might be more fitting as a separate PR. 

Thank you for your valuable contribution to this project!

**Comment by Mohd-PH** [comment]
Thank you for your input on this

I'll try to do the dropdown menu as you suggested

Search function and grouping the project is coming up next 😄

**Comment by Alaboudi1** [comment]
This is much better than the tabs, thanks! 

I was going through the code and had one question about projects.json. Why are we storing it in the repo? Is this an optimization so we do not create a list of projects each time a merge occurs?

My initial intuition about how this was implemented was much simpler :). You fetched the dev.json file, iterated over each project, pulled the information, and used Promise.all to fetch concurrently.

My question is: does the way you did it have any benefit over simply doing this?
`
Promise.all(projects.map(url => 
    fetch(url)
    .then(response => response.json())
    .then(data => {
        .......
    })
`

Please let me know what do think so we can merge this useful addition as soon as possible!

**Comment by Mohd-PH** [comment]
I believe Promise.all will send all the requests at once and wait for their responses, but as the github api is rate limited depending on the account requesting it (guests have 60 requests per hour), it is better to send 1 request at a time and sleep for a minute before sending the next request.

**Comment by Alaboudi1** [comment]
I forgot about the GitHub rate limit, and I see now why storing project data is necessary 👍🏽 

However, I am still thinking the code can be further simplified.

What if we did everything inside dev.json? When a developer wants to add a new project, they would only need to add the primary fields in the template.md. From there, we could construct the HTML table based on these new additions (which we are already doing ), *and THEN populate the dev.json with additional project details*. This approach eliminates the need for a separate project.json file. Also makes it much easier to only request project data for the newly added projects.

What do you think?

**Comment by Mohd-PH** [comment]
Done

**Comment by Alaboudi1** [comment]
@Mohd-PH I need your feedback on a few things.

1. combined the two workflows into one and made all the data transformation in one file OSS-update-readme.
2.  I think you we using `const client = new octokit.Octokit({ auth: process.env.GITHUB_TOKEN });` which makes our request authenticated, right? We are not limited to the 60 req/h. Just so you know- I have made a few changes accordingly. 

Please review the changes and let me know if there is any issue with what I have introduced in the code before merging.

Thanks!

**Comment by Mohd-PH** [comment]
Yeah I believe the limit is 1000 request per hour, this way it is still sending all the requests at once, but it should be safe, we won't reach 1000 anyways 
 
I would return `project` at line 75 in `OSS-update-readme.js` because we are just sleeping without sending another request to get the details, so it is bound to fail after 'waking up' at line 79 

another thing, how did you push to my fork? I thought github doesn't allow that 🥲

**Comment by Alaboudi1** [comment]
@Mohd-PH Sorry for pushing directly into your branch. I thought making the small changes myself was faster than asking you to make them, but I should have done it through a pull request 🙃.

Can you make the changes that you suggest? If you do not have the time, I certainly can make them and merge this work. I think it is ready!

**Comment by Mohd-PH** [comment]
It's totally ok but I thought github doesn't allow it that's all. maybe because I've already submitted this pull request it gave you access.

Just submitted the change 

Thank you 😄

**Comment by Mohd-PH** [comment]
My pleasure 🤖 

I don't know why the workflow keeps on failing with 403 error 😢

**Comment by Alaboudi1** [comment]
Is it a regression, did you changes something that cause this?

**Comment by Mohd-PH** [comment]
It was failing before since the last template edit, at that time I didn't change the permission for the workflow 

after that I tried to give it per job permission to write content, but it keeps on failing with the same error

**Comment by Alaboudi1** [comment]
cli bugs are the worst!

I may have more time next week to deep into this issue and see if I can figure it out. But feel free to debug it if you have time until then.

**Comment by Mohd-PH** [comment]
Sure thing, thank you

**Pull request merged**
